[package]
name = "morello"
version = "0.1.0"
edition = "2021"
default-run = "morello"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
auto_impl = "1.1.0"
by_address = "1.1.0"
clap = { version = "4.2.5", features = ["derive"] }
crossbeam-channel = "0.5.8"
divrem = "1.0.0"
enum-iterator = "1.4.1"
enum_dispatch = "0.3.11"
env_logger = "0.10.0"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.0"
prettytable-rs = "^0.10"
rand = "0.8.5"
rayon = "1.7.0"
rusqlite = "0.29.0"
scc = "1.7.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
smallvec = {version = "1.10.0", features = ["serde"]}
thread_local = "1.1.7"

[profile.release]
debug = 1

[dev-dependencies]
iai-callgrind = "0.4.0"
proptest = "1.2.0"

[[bench]]
name = "iter_actions"
harness = false

[[bench]]
name = "synth"
harness = false
