[package]
name = "morello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
divrem = "1.0.0"
env_logger = "0.9.0"
itertools = "0.10.5"
log = "0.4.0"
prettytable-rs = "^0.10"
rusqlite = "0.29.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
smallvec = {version = "1.10.0", features = ["serde"]}

[profile.release]
debug = 1
