name: morello
channels:
  # - tlcpack
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - clang==13.0.1
  - llvm-openmp==13.0.1
  - compiler-rt==13.0.1
  - compiler-rt_linux-64==13.0.1
  - llvmdev==13.0.1
  - tabulate
  - frozendict~=2.0
  - pyarrow
  - pandas
  - tqdm
  - pytest
  - pytest-xdist
  - debugpy
  - hypothesis==6.47.1
  - atomicwrites==1.4.0
  - termcolor==1.1.0
  - sympy
  - typeguard
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-auth-oauthlib
  - pydrive2
  - gspread
  - pytorch=1.11.0
  - jax==0.3.13
  - tvm-py=0.8.0
  - libtvm=0.8.0
  - gcc  # Required to build Cython
  - pip:
    - git+https://github.com/cython/cython.git@dc5f0de75638c7b39650c7542ad0779e5eddb38b
variables:
  CLANG: ${CONDA_PREFIX}/bin/clang
  LIBRARY_PATH: ${CONDA_PREFIX}/lib
