[tool.isort]
profile = "black"
skip = ["setup.py"]

[tool.pytest.ini_options]
minversion = 6.0
addopts = "--strict-markers --doctest-modules"
testpaths = [ "tests" ]
markers = [
    "slow: test is time-consuming.",
    "hexagon: test needs hexagon-sim.",
    "parallelspec: test of is a Spec/Impl with a parallel loop.",
]
