name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: cargo run matmul 4

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - run: cargo clippy --all-targets --all-features -- -D clippy::all -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
